SongTrade/Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using SongTrade.Auth;
using SongTrade.DataAccess.Repository.IRepository;
using SongTrade.Models;
using SongTrade.Models.ViewModel;
using SongTrade.Utility;
using System.IdentityModel.Tokens.Jwt;
using System.Net.Http.Headers;
using System.Security.Claims;
using System.Security.Cryptography;using System.Text;
using Controller = Microsoft.AspNetCore.Mvc.Controller;
using HttpPostAttribute = Microsoft.AspNetCore.Mvc.HttpPostAttribute;
using ValidateAntiForgeryTokenAttribute = Microsoft.AspNetCore.Mvc.ValidateAntiForgeryTokenAttribute;

namespace SongTrade.Controllers
{
    public class AuthController : Controller
    {
        private readonly IUserRepository _userRepo;
        private readonly IAuthService _auth;

        public AuthController(IAuthService auth, IUserRepository userRepo)
        {
            _userRepo = userRepo;
            _auth = auth;
        }

        //register
        public IActionResult Index()
        {       
            return View();
        }

        //register - post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(UserDto request)
        {
            var userFromDb = _userRepo.GetFirstOrDefault(u => u.Username == request.Username);

            if (userFromDb != null)
            {
                ModelState.AddModelError("Username", "Username already exists");
                return View(request);
            }

            _auth.CreatePasswordHash(request.Password, out byte[] passwordHash, out byte[] passwordSalt);

            User user = new User();
            user.TypeOfUser = request.TypesOfUser;
            user.Username = request.Username;
            user.PasswordHash = passwordHash;
            user.PasswordSalt = passwordSalt;
            user.Name = request.Name;

            _userRepo.Add(user);
            _userRepo.Save();

            string token = _auth.CreateToken(user);
            HttpContext.Session.SetString(StaticDetails.UserToken, token);
            HttpContext.Session.SetString(StaticDetails.Role, user.TypeOfUser);
            HttpContext.Session.SetString(StaticDetails.UserId, user.Id.ToString());
            HttpContext.Session.SetString(StaticDetails.Username, user.Username.ToString());

            TempData["success"] = "You register successfully";

            return RedirectToAction("Index", "Home");
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Login(UserDto request)
        {
            var userFromDb = _userRepo.GetFirstOrDefault(u => u.Username == request.Username);

            if (userFromDb != null)
            {
                if (_auth.VerifyPasswordHash(request.Password, userFromDb.PasswordHash, userFromDb.PasswordSalt))
                {
                    string token = _auth.CreateToken(userFromDb);
                    HttpContext.Session.SetString(StaticDetails.UserToken, token);
                    HttpContext.Session.SetString(StaticDetails.Role, userFromDb.TypeOfUser);
                    HttpContext.Session.SetString(StaticDetails.UserId, userFromDb.Id.ToString());
                    HttpContext.Session.SetString(StaticDetails.Username, userFromDb.Username.ToString());

                    TempData["success"] = "You logged in successfully";
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError("Password", "Password is not correct");
                }
            }
            else
            {
                ModelState.AddModelError("Username", "Username doesn't exist");
            }

            return View(request);
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            TempData["success"] = "You logged out successfully";
            return RedirectToAction("Index", "Home");
        }
 
    }
}

SongTrade/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SongTrade.Authorization;
using SongTrade.DataAccess.Repository.IRepository;
using SongTrade.Models;
using SongTrade.Models.ViewModel;
using SongTrade.Utility;
using Stripe.Checkout;

namespace SongTrade.Controllers
{
    public class CartController : Controller
    {
        private readonly IShoppingCartRepository _cartRepo;
        private readonly IOrderHeaderRepository _orderHeaderRepo;
        private readonly IOrderDetailRepository _orderDetailsRepo;
        [BindProperty]
        public ShoppingCartVM ShoppingCartVM { get; set; }

        public CartController(IShoppingCartRepository cartRepo, IOrderHeaderRepository orderHeaderRepo, IOrderDetailRepository orderDetailsRepo)
        {
            _cartRepo = cartRepo;
            _orderHeaderRepo = orderHeaderRepo;
            _orderDetailsRepo = orderDetailsRepo;
        }

        [AuthRole("Role", "buyer")]
        public IActionResult Index(string buyerId)
        {
            if (buyerId != null)
            {
                ShoppingCartVM = new ShoppingCartVM()
                {
                    ShoppingCarts = _cartRepo.GetAll(c => c.UserId == int.Parse(buyerId), includeProperties: "Song"),
                    OrderHeader = new()
                };
                foreach (var item in ShoppingCartVM.ShoppingCarts)
                {
                    ShoppingCartVM.OrderHeader.OrderTotal += item.Song.Price;
                }
                return View(ShoppingCartVM);
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Index")]
        public IActionResult IndexPOST()
        {
            var userIdString = HttpContext.Session.GetString(StaticDetails.UserId);
            var userId = int.Parse(userIdString);
            ShoppingCartVM = new ShoppingCartVM()
            {
                ShoppingCarts = _cartRepo.GetAll(c => c.UserId == userId,
                    includeProperties: "Song"),
                OrderHeader = new()
                {
                    CreatedAt = DateTime.Now,
                    UserId = userId
                }
            };

            foreach (var item in ShoppingCartVM.ShoppingCarts)
            {
                ShoppingCartVM.OrderHeader.OrderTotal += item.Song.Price;
            }

            _orderHeaderRepo.Add(ShoppingCartVM.OrderHeader);
            _orderHeaderRepo.Save();

            //stripe payment
            var domain = "https://localhost:44348/";
            var options = new SessionCreateOptions
            {
                PaymentMethodTypes = new List<string>
                {
                    "card"
                },
                LineItems = new List<SessionLineItemOptions>(),
                Mode = "payment",
                SuccessUrl = domain + $"cart/OrderConfirmation?id={ShoppingCartVM.OrderHeader.Id}",
                CancelUrl = domain + $"cart/index?buyerId={userIdString}"
            };

            foreach (var item in ShoppingCartVM.ShoppingCarts)
            {
                var sesstionLineItem = new SessionLineItemOptions
                {
                    PriceData = new SessionLineItemPriceDataOptions
                    {
                        UnitAmount = (long)(item.Song.Price * 100),
                        Currency = "usd",
                        ProductData = new SessionLineItemPriceDataProductDataOptions
                        {
                            Name = item.Song.Title
                        }
                    },
                    Quantity = 1
                };
                options.LineItems.Add(sesstionLineItem);
            }

            var service = new SessionService();
            Session session = service.Create(options);

            ShoppingCartVM.OrderHeader.PaymentIntentId = session.PaymentIntentId;
            ShoppingCartVM.OrderHeader.SessionId = session.Id;

            //saving order to db
            _orderHeaderRepo.Update(ShoppingCartVM.OrderHeader);
            _orderHeaderRepo.Save();

            //saving order details to db
            foreach (var item in ShoppingCartVM.ShoppingCarts)
            {
                OrderDetail detail = new OrderDetail()
                {
                    OrderId = ShoppingCartVM.OrderHeader.Id,
                    SongId = item.SongId,
                    Price = item.Song.Price
                };
                _orderDetailsRepo.Add(detail);
                _orderDetailsRepo.Save();
            }
            Response.Headers.Add("Location", session.Url);
            return new StatusCodeResult(303);
        }

        public IActionResult Remove(int cartId)
        {
            var cartFromDb = _cartRepo.GetFirstOrDefault(c => c.Id == cartId);
            _cartRepo.Remove(cartFromDb);
            _cartRepo.Save();
            var buyerId = cartFromDb.UserId.ToString();
            return RedirectToAction("Index", new { buyerId });
        }

        public IActionResult OrderConfirmation(int id)
        {
            int userId = int.Parse(HttpContext.Session.GetString(StaticDetails.UserId));
            IEnumerable<ShoppingCart> carts = _cartRepo.GetAll(c => c.UserId == userId);
            _cartRepo.RemoveRange(carts);
            _cartRepo.Save();
            return View(id);
        }
    }
}

SongTrade/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using SongTrade.Authorization;
using SongTrade.DataAccess.Repository.IRepository;
using SongTrade.Models;
using SongTrade.Utility;
using System.Globalization;
using System.Web.WebPages;

namespace SongTrade.Controllers
{
    [AuthRole("Role", "buyer")]
    public class OrderController : Controller
    {
        
        private readonly IOrderHeaderRepository _orderRepo;

        public OrderController(IOrderHeaderRepository orderRepo)
        {
            _orderRepo = orderRepo;
        }

        public IActionResult Index()
        {
            return View();  
        }

        [HttpGet]
        public IActionResult GetAll()
        {
            int userId = int.Parse(HttpContext.Session.GetString(StaticDetails.UserId));
            IEnumerable<OrderHeader> orders = _orderRepo.GetAll(o => o.UserId == userId);
            return Json(new { data = orders });
        }
    }
}

SongTrade/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SongTrade</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/bootswatch.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.1/css/jquery.dataTables.min.css"/>
    <link rel="stylesheet" href="~/SongTrade.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SongTrade</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Song" asp-action="Index" asp-route-pageNumber=1 asp-route-pageSize=6>Find Songs</a>
                        </li>
                        @if (Context.Session.GetString("Role") == "author")
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">My Songs</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item text-dark" asp-controller="Song" asp-action="Add">Add Song</a>
                                    <a class="dropdown-item text-dark" asp-controller="Song" asp-action="GetByUser" asp-route-userId="@Context.Session.GetString("UserId")">My Songs</a>
                                </div>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Song" asp-action="SoldSongs">Sold Songs</a>
                            </li>
                        }
                        @if (Context.Session.GetString("Role") == "buyer")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Cart" asp-action="Index"
                                    asp-route-buyerId="@Context.Session.GetString("UserId")">
                                    <i class="bi bi-cart"></i></a>
                            </li>
                        }
                        @if (Context.Session.GetString("Role") == "buyer")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Song" asp-action="GetByBuyer"
                                    asp-route-buyerId="@Context.Session.GetString("UserId")">
                                    My Songs
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Order" asp-action="Index">
                                    My Orders
                                </a>
                            </li>
                        }
                    </ul>
                    <ul class="navbar-nav">
                        @if (Context.Session.GetString("Role") == null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Auth" asp-action="Index">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Auth" asp-action="Login">Login</a>
                            </li>
                        }
                        @if (Context.Session.GetString("Role") == "author" || Context.Session.GetString("Role") == "buyer")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark">Hi @Context.Session.GetString("Username")</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Auth" asp-action="Logout">Logout</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="//cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdn.tiny.cloud/1/rtiij6rcju48zel3lf0wsrcvj8rbxhrvnrxmgz0ik0nodwd0/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SongTrade/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}